CC=gcc
CXX=g++
#CXX=clang++
CFLAGS=-Wall -Wextra -Iincludes -I../shared/includes -O2
CXXFLAGS=-Wall -Wextra -std=c++11 -Weffc++ -Iincludes -I../shared/includes -g -O2
VPATH=../shared/src:src:includes

clean: 
	rm -rf *~ *.o main

.PHONY: all clean
