CC=gcc
CXX=g++
#CXX=clang++
CFLAGS=-Wall -Wextra -Wcast-align -Iincludes -I../shared/includes -ggdb -O2
CXXFLAGS=-Wall -Wextra -Wcast-align -std=c++11 -Weffc++ -Iincludes -I../shared/includes -ggdb -O2
VPATH=../shared/src:src:includes


default: all # to be defined in children

clean: clean_extra
	rm -rf *~ includes/*~ src/*~ *.o

../shared/%.o: ../shared/src/%.cpp
	$(MAKE) -C ../shared $(subst ../shared/, , $@)

.PHONY: all clean default clean_extra
